module.exports = {
    staysTypes: Object.freeze({
        villa: {
            name: "Villa",
            value: 0,
        },
        apartment: {
            name: "Apartment",
            value: 1,
        },
        cruise: {
            name: "Cruise",
            value: 2,
        },
        hotel: {
            name: "Hotel",
            value: 3,
        },
    }),
    amenities: Object.freeze({
        wifi: {
            name: "Free Wi-Fi",
            value: 1,
            selected: true,
            icon: "wifi",
        },
        complimentaryBreakfast: {
            name: "Complimentary Breakfast",
            value: 2,
            selected: true,
            icon: "coffee",
        },
        airConditioning: {
            name: "Air Conditioning",
            value: 3,
            selected: true,
            icon: "wind",
        },
        minibar: {
            name: "Minibar",
            value: 4,
            selected: true,
            icon: "glass",
        },
        luxuryToiletries: {
            name: "Luxury Toiletries",
            value: 5,
            selected: true,
            icon: "gift",
        },
        inRoomSafe: {
            name: "In-room Safe",
            value: 6,
            selected: true,
            icon: "lock",
        },
        flatScreenTV: {
            name: "Flat-screen TV",
            value: 7,
            selected: true,
            icon: "tv",
        },
        coffeeMaker: {
            name: "Coffee/Tea Maker",
            value: 8,
            selected: true,
            icon: "coffee",
        },
        privateBalcony: {
            name: "Private Balcony/Terrace",
            value: 9,
            selected: true,
            icon: "sun",
        },
        jacuzzi: {
            name: "Private Hot Tub or Jacuzzi",
            value: 10,
            selected: true,
            icon: "droplet",
        },
        roomService: {
            name: "Room Service",
            value: 11,
            selected: true,
            icon: "tray",
        },
        butler: {
            name: "Butler",
            value: 12,
            selected: true,
            icon: "user-check",
        },
        privateChef: {
            name: "Private Chef",
            value: 13,
            selected: true,
            icon: "chef-hat",
        },
        swimmingPool: {
            name: "Swimming Pool",
            value: 14,
            selected: true,
            icon: "waves",
        },
        petFriendly: {
            name: "Pet-friendly Rooms",
            value: 15,
            selected: true,
            icon: "paw",
        },
        bbqFacilities: {
            name: "BBQ Facilities",
            value: 16,
            selected: true,
            icon: "grill",
        },
    }),
    attractions: Object.freeze({
        spaServices: {
            name: "Spa and Wellness Center",
            value: 1,
            selected: true,
            icon: "spa",
        },
        fitnessCenter: {
            name: "Fitness Center/Gym",
            value: 2,
            selected: true,
            icon: "dumbbell",
        },
        conciergeService: {
            name: "Concierge Service",
            value: 3,
            selected: true,
            icon: "briefcase",
        },
        onSiteRestaurant: {
            name: "On-site Restaurant",
            value: 4,
            selected: true,
            icon: "utensils",
        },
        businessCenter: {
            name: "Business Center",
            value: 5,
            selected: true,
            icon: "briefcase",
        },
        frontDesk: {
            name: "24/7 Front Desk Service",
            value: 6,
            selected: true,
            icon: "clock",
        },
        airportShuttle: {
            name: "Airport Shuttle Service",
            value: 7,
            selected: true,
            icon: "airplane",
        },
        carRental: {
            name: "Car Rental Service",
            value: 8,
            selected: true,
            icon: "car",
        },
        laundryService: {
            name: "Laundry/Dry Cleaning Service",
            value: 9,
            selected: true,
            icon: "shirt",
        },
        complimentaryParking: {
            name: "Complimentary Parking",
            value: 10,
            selected: true,
            icon: "parking",
        },
        evChargingStations: {
            name: "Electric Vehicle Charging Stations",
            value: 11,
            selected: true,
            icon: "battery-charging",
        },
        kidsClub: {
            name: "Kids Club/Childcare Services",
            value: 12,
            selected: true,
            icon: "child",
        },
        privateBeachAccess: {
            name: "Private Beach Access",
            value: 13,
            selected: true,
            icon: "umbrella",
        },
        outdoorActivities: {
            name: "Outdoor Activities",
            value: 14,
            selected: true,
            icon: "compass",
        },
        wineTasting: {
            name: "Wine Tasting/On-site Bar",
            value: 15,
            selected: true,
            icon: "wine-glass",
        },
    }),
};
