POST http://localhost:5000/api/auth/register HTTP/1.1
content-type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "john.2doe@example.com",
    "password": "securepassword123",
    "phone": "+91 11233223",
    "state": "CA",
    "country": "USA",
    "postalCode": "12345"
}