const validator = require("validator");
const bcrypt = require("bcryptjs");
const authConfig = require("../features/auth/auth.config");
const { Field } = require("../utils/schemas");
const Workspace = require("./workspace.schema");
const User = require("./user.schema");

module.exports = {
    $schemaName: "Auth",
    $apiSlug: "auth",
    workspace: new Field({
        name: "Workspace",
        type: Workspace,
        required: true,
        default: null,
        enum: null,
        // validator: (value) => validator.isMongoId(value),
        // errorMessage: "Must be a valid MongoId",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    user: new Field({
        name: "User",
        type: User,
        required: true,
        default: null,
        enum: null,
        // validator: (value) => validator.isMongoId(value),
        // errorMessage: "Must be a valid MongoId",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    role: new Field({
        name: "Role",
        type: Number,
        required: true,
        default: authConfig.userWorkspaceRoles.admin,
        enum: Object.values(authConfig.userWorkspaceRoles),
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
    }),
    type: new Field({
        name: "Type",
        type: Number,
        required: true,
        default: authConfig.workspaceTypes.profile,
        enum: Object.values(authConfig.workspaceTypes),
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    scope: new Field({
        name: "Scope",
        type: Number,
        required: true,
        default: authConfig.workspaceScopes.profile,
        enum: Object.values(authConfig.workspaceScopes),
        validator: null,
        errorMessage: "",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a - b,
        sortDesc: (a, b) => b - a,
        filter: (type, check) => +type === +check,
    }),
    username: new Field({
        name: "Username",
        type: String,
        required: false,
        default: null,
        enum: null,
        validator: (value) => validator.isLength(value, { min: 3 }),
        errorMessage: "Should be atleast 3 characters long",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a.localeCompare(b),
        sortDesc: (a, b) => b.localeCompare(a),
        filter: (username, check) => username.toLowerCase().includes(check.toLowerCase()),
    }),
    email: new Field({
        name: "Email",
        type: String,
        required: true,
        default: null,
        enum: null,
        validator: (value) => validator.isEmail(value),
        errorMessage: "Should be a valid email",
        showInTable: true,
        showInForm: true,
        fullwidth: false,
        sortAsc: (a, b) => a.localeCompare(b),
        sortDesc: (a, b) => b.localeCompare(a),
        filter: (email, check) => email.toLowerCase().includes(check.toLowerCase()),
    }),
    password: new Field({
        name: "Password",
        type: String,
        required: true,
        default: null,
        enum: null,
        validator: (value) => validator.isStrongPassword(value),
        errorMessage:
            "Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, one number, and one special character",
        select: false,
        showInTable: false,
        showInForm: true,
        fullwidth: false,
    }),
    oAuth: {
        google: new Field({
            name: "Google",
            type: Object,
            required: false,
            default: null,
            enum: null,
            validator: null,
            errorMessage: "",
            showInTable: true,
            showInForm: false,
            fullwidth: false,
        }),
        facebook: new Field({
            name: "Facebook",
            type: Object,
            required: false,
            default: null,
            enum: null,
            validator: null,
            errorMessage: "",
            showInTable: true,
            showInForm: false,
            fullwidth: false,
        }),
        linkedin: new Field({
            name: "LinkedIn",
            type: Object,
            required: false,
            default: null,
            enum: null,
            validator: null,
            errorMessage: "",
            showInTable: true,
            showInForm: false,
            fullwidth: false,
        }),
        apple: new Field({
            name: "Apple",
            type: Object,
            required: false,
            default: null,
            enum: null,
            validator: null,
            errorMessage: "",
            showInTable: true,
            showInForm: false,
            fullwidth: false,
        }),
        github: new Field({
            name: "Github",
            type: Object,
            required: false,
            default: null,
            enum: null,
            validator: null,
            errorMessage: "",
            showInTable: true,
            showInForm: false,
            fullwidth: false,
        }),
    },
    pre: {
        save: async function (next) {
            if (!this.isModified("password")) return next();
            const salt = await bcrypt.genSalt(10);
            this.password = await bcrypt.hash(this.password, salt);
            return next();
        },
    },
    methods: {
        matchPassword: async function (enteredPassword) {
            return await bcrypt.compare(enteredPassword, this.password);
        },
    },
};
